// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pflubgfayjhcwhondcdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmbHViZ2ZheWpoY3dob25kY2R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMjE3OTAsImV4cCI6MjA2ODc5Nzc5MH0.Eh3C9V16j9ZxhY-BjOYwuwysM1gNpUVoJb1x_YZtnTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});